/*
	Lime's full custom SDL2 configuration.

	This directory (custom/sdl) is placed first on the include path and the SDL
	build is compiled with -DUSING_GENERATED_CONFIG_H, so SDL and Lime both use
	the configuration here instead of SDL's in-tree include/SDL_config.h. Every
	config value lives in these files and is ours to edit.

	This header just selects the right per-target config below; all of them are
	full, self-contained copies of SDL2's static configs (complete default
	backend set) that you can customize freely. Add project-wide defines in the
	"Lime overrides" block so they apply to every target from one place.
*/

#ifndef SDL_config_h_
#define SDL_config_h_

#include "SDL_platform.h"

/* ------------------------------------------------------------------------- */
/* Lime overrides (applied on every target, before the per-target config).    */
/* ------------------------------------------------------------------------- */


/* ------------------------------------------------------------------------- */
/* Per-target configuration (our editable copies in custom/sdl/).             */
/* ------------------------------------------------------------------------- */
#if defined(__WIN32__) || defined(__WINGDK__)
#include "SDL_config_windows.h"
#elif defined(__WINRT__)
#include "SDL_config_winrt.h"
#elif defined(__MACOSX__)
#include "SDL_config_macosx.h"
#elif defined(__IPHONEOS__)
#include "SDL_config_iphoneos.h"
#elif defined(__ANDROID__)
#include "SDL_config_android.h"
#elif defined(__EMSCRIPTEN__)
#include "SDL_config_emscripten.h"
#else
/* Linux/other Unix have no static config upstream (normally generated by
   configure/CMake). Falls back to the minimal config; replace with a curated
   custom/sdl/SDL_config_linux.h for a full Linux build. */
#include "SDL_config_minimal.h"
#endif

#endif /* SDL_config_h_ */
